# @package _global_

model:
  name: ets
  trend: add
  damped_trend: false
  seasonal: null
  seasonal_periods: null
  use_boxcox: null
  initialization_method: estimated

training:
  epochs: 2
  learning_rate: 0.001
  weight_decay: 0.0
  grad_clip: null
  log_interval: 10
  device: cpu
